In [3]:
import nltk
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

DATA COLLECTION 

In [4]:
data_fake = pd.read_csv('Fake.csv')
data_true = pd.read_csv('True.csv')

In [5]:
data_fake["class"] = 0
data_true["class"] = 1

In [6]:
data_fake.shape, data_true.shape

((5000, 5), (5000, 5))

DATA PREPROCESSING 

In [7]:
data_merge = pd.concat([data_fake, data_true], axis=0)
data_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [8]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [9]:
data = data_merge.drop(['subject','date'], axis = 1)

In [10]:
data.isnull().sum()

title    0
text     0
class    0
dtype: int64

In [11]:
data = data.sample(frac = 1)

In [12]:
data.reset_index(inplace = True)
data.drop(['index'], axis = 1, inplace = True)

In [13]:
data.columns

Index(['title', 'text', 'class'], dtype='object')

In [14]:
data.head()

title  \
0   Trump Tweets About His Impeachment Chances In...   
1   Notorious RBG Throws AMAZING Shade At Trump F...   
2  UK's Farage 'person of interest' in Trump-Russ...   
3  U.S. Treasury vows no special treatment for Tr...   
4  Trump backs New York in bourses' battle for Sa...   

                                                text  class  
0  Nothing betrays your official narrative that y...      0  
1  We love Ruth Bader Ginsburg. She s the sweet  ...      0  
2  LONDON (Reuters) - Brexit campaigner Nigel Far...      1  
3  WASHINGTON (Reuters) - U.S. Treasury Secretary...      1  
4  WASHINGTON/KHOBAR, Saudi Arabia (Reuters) - U....      1

DATA CLEANING 

In [15]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
nltk.download('stopwords')
nltk.download('punkt')

def preprocessing(text):
    text = text.lower()
    text = re.sub('\[.*?\]','',text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+','',text)
    text = re.sub('<.*?>+','',text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*','',text)
    text = re.sub('[%s]' % re.escape(string.punctuation) ,'',text)  #Removes all punctuation characters using string.punctuation
    words = word_tokenize(text)                 #Tokenize the words
    stop_words = set(stopwords.words('english'))    #stores all stopwords in english as a set stop_words
    words = [word for word in words if word not in stop_words]  #remove stopwords
    stemmer = PorterStemmer()               #porterstemmer initializes to stemmer 
    words = [stemmer.stem(word) for word in words]  #stemming process
    text = ' '.join(words)                  #Joins all the words after stopwords removal and stemmming as a text
    return text


[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [52]:
text=preprocessing("WASHINGTON (Reuters) - U.S. President Donald Trump signed Republicans’ massive $1.5 trillion tax overhaul into law on Friday, cementing the biggest legislative victory of his first year in office, and also approved a short-term spending bill that averts a possible government shutdown. Trump said he wanted to sign the tax bill before leaving Washington on Friday for his Mar-a-Lago estate in Florida, rather than stage a more formal ceremony in January, so he could keep his promise to finish work before Christmas. “I didn’t want you folks to say I wasn’t keeping my promise. I’m keeping my promise,” he told reporters in the White House. The two pieces of legislation represent Trump’s most significant accomplishment with Congress since taking office in January, as well as a sign of what awaits when he returns from Florida after the Christmas holiday. The tax package, the largest such overhaul since the 1980s, slashes the corporate rate from 35 percent to 21 percent and temporarily reduces the tax burden for most individuals as well. Trump praised several companies that have announced employee bonuses in the wake of the bill’s passage, naming AT&T, Boeing, Wells Fargo, Comcast  and Sinclair Broadcast Group. “Corporations are literally going wild over this,” he said.      Democrats had opposed the bill as a giveaway to the wealthy that would add $1.5 trillion to the $20 trillion national debt during the next decade. The spending bill extends federal funding through Jan. 19, largely at current levels. It does nothing to resolve broader disputes over immigration, healthcare and military spending. Republicans also are divided over whether to follow up their sweeping overhaul of the U.S. tax code with a dramatic restructuring of federal benefit programs. House Speaker Paul Ryan has said he would like to revamp welfare and health programs but Senate Republican Leader Mitch McConnell told National Public Radio on Monday that he was not interested in cutting those programs without Democratic support. Trump’s year also closes with significant turnover of many top staffers who had been in the White House since early in his term. On Friday, the White House confirmed Deputy Chief of Staff Rick Dearborn and Jeremy Katz, who worked under White House economic adviser Gary Cohn, were leaving. ")


In [53]:
tokens=word_tokenize(text)
print(len(tokens))

237


In [17]:
data['text'] = data['text'].apply(preprocessing)
data['title'] = data['title'].apply(preprocessing)
data.head(10)

title  \
0  trump tweet impeach chanc latest perhap greate...   
1  notori rbg throw amaz shade trump scotu bench ...   
2  uk farag person interest trump russia investig...   
3  u treasuri vow special treatment trump invest ...   
4  trump back new york bours battl saudi aramco list   
5  florida school overreact prank press feloni charg   
6  ex cia head say trump remark russia interfer d...   
7   trump voter fraud panel meet u state refus mount   
8  trump commit obstruct justic whine comey leak ...   
9  pelosi say trump abus power interact ex fbi chief   

                                                text  class  
0  noth betray offici narr administr function wel...      0  
1  love ruth bader ginsburg sweet also sharp libe...      0  
2  london reuter brexit campaign nigel farag pers...      1  
3  washington reuter u treasuri secretari steven ...      1  
4  washington khobar saudi arabia reuter u presid...      1  
5  three year old girl charg first degre feloni l...      1  
6  aspen colo reuter former cia director john bre...      1  
7  washington reuter presid donald trump commiss ...      1  
8  donald trump broke twitter silenc jame comey s...      0  
9  washington reuter democrat leader u hous repre...      1

FEATURE SELECTION 

In [18]:
data['combined'] = data['title']+data['text']
x = data['combined']
y = data['class']

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25)
print(x_test.info())

<class 'pandas.core.series.Series'>
Index: 2500 entries, 8591 to 3863
Series name: combined
Non-Null Count  Dtype 
--------------  ----- 
2500 non-null   object
dtypes: object(1)
memory usage: 39.1+ KB
None


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
print(x_test.head(10))
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)
print(xv_test)
from joblib import dump
dump(vectorization, 'f.joblib')

8591    trump voter panick realiz border wall put hous...
5416    take back control uk classic blue gold passpor...
5718    senat tax bill stall deficit focus triggerwash...
3377    white hous want healthcar vote summer tax refo...
7028    sanction silver line russian chees producistra...
1161    republican revamp u health bill boost benefit ...
2106    suprem court put huge stake heart first amendr...
6015    dem senat increasingli concern trump fire muel...
1464    trump order eas ban polit activ churchwashingt...
9179    pat mccrori bigot bathroom law cost nc million...
Name: combined, dtype: object
  (0, 36056)	0.01806872853616025
  (0, 35817)	0.04556729110870538
  (0, 35811)	0.04542828753025756
  (0, 35756)	0.021597073160367502
  (0, 35050)	0.026821297036472926
  (0, 34915)	0.24595596859486354
  (0, 34790)	0.13671696497392155
  (0, 34190)	0.01858336151513587
  (0, 33899)	0.02253435118522806
  (0, 33876)	0.07936237661480801
  (0, 33566)	0.043490079209966316
  (0, 33460)	0.049213222

['f.joblib']

TRAINING AND TESTING OF THE MODEL 

Random Forest -

In [21]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(random_state = 0)
RF.fit(xv_train, y_train)

RandomForestClassifier(random_state=0)

In [22]:
from joblib import dump
dump(RF, 'RF.pk1')

['RF.pk1']

In [23]:
pred_rf = RF.predict(xv_test)
print(pred_rf)

[0 1 1 ... 0 1 0]


In [24]:
print(" Random Forest Accuracy = ",RF.score(xv_test, y_test))

 Random Forest Accuracy =  0.9156


In [25]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

cm_rf = confusion_matrix(y_test, pred_rf)
print("Confusion Matrix for Random Forest:")
print(cm_rf)

# Assuming cm_rf is the confusion matrix from your random forest predictions
tn, fp, fn, tp = cm_rf.ravel()

precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix for Random Forest:
[[1104  108]
 [ 103 1185]]
Precision: 0.9164733178654292
Recall: 0.9200310559006211
F1 Score: 0.9182487407981402


In [26]:
from sklearn.ensemble import RandomForestClassifier

def predict_news_rf(input_text):
    input_text = preprocessing(input_text)
    input_vector = vectorization.transform([input_text])
    prediction = RF.predict(input_vector)
    return "Fake" if prediction[0] == 0 else "Real"

input_text =""
prediction_rf = predict_news_rf(input_text)
print(f"The input text is predicted as: {prediction_rf}")

The input text is predicted as: Real


LOGISTIC REGRESSION -

In [27]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train, y_train)


LogisticRegression()

In [28]:
dump(LR, 'LR.pk1')

['LR.pk1']

In [29]:
pred_lr = LR.predict(xv_test)

In [30]:
print(" Logistic Regression Accuracy = ",LR.score(xv_test, y_test))

 Logistic Regression Accuracy =  0.9208


In [31]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

cm_rf = confusion_matrix(y_test, pred_lr)
print("Confusion Matrix for Logistic Regression :")
print(cm_rf)

# Assuming cm_rf is the confusion matrix from your random forest predictions
tn, fp, fn, tp = cm_rf.ravel()

precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Confusion Matrix for Logistic Regression :
[[1106  106]
 [  92 1196]]
Precision: 0.9185867895545314
Recall: 0.9285714285714286
F1 Score: 0.9235521235521235


In [32]:
def predict_news(input_text):
    input_text = preprocessing(input_text)
    input_vector = vectorization.transform([input_text])
    prediction = LR.predict(input_vector)
    return "Fake" if prediction[0] == 0 else "Real"

input_text =" "
prediction = predict_news(input_text)
print(f"The input text is predicted as: {prediction}")


The input text is predicted as: Real


SVM

In [33]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svm_classifier = SVC(kernel='linear')

svm_classifier.fit(xv_train, y_train)

SVC(kernel='linear')

In [34]:
from joblib import dump
dump(svm_classifier, 'SVM.pk1')

['SVM.pk1']

In [35]:
y_pred = svm_classifier.predict(xv_test)

In [36]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(" SVM Accuracy = ",accuracy)

 SVM Accuracy =  0.9316


In [37]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

cm_svm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix for SVM :")
print(cm_svm)

# Assuming cm_rf is the confusion matrix from your random forest predictions
tn, fp, fn, tp = cm_svm.ravel()

precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Confusion Matrix for SVM :
[[1110  102]
 [  69 1219]]
Precision: 0.9227857683573051
Recall: 0.9464285714285714
F1 Score: 0.9344576466078958


In [38]:
def predict_news_svm(input_text):
    input_text = preprocessing(input_text)
    input_vector = vectorization.transform([input_text])
    prediction = svm_classifier.predict(input_vector)
    return "Fake" if prediction[0] == 0 else "Real"

input_text = " "
prediction = predict_news_svm(input_text)
print(f"The input text is predicted as: {prediction}")

The input text is predicted as: Real


PASSIVE AGRESSIVE CLASSIFER

In [39]:
from sklearn.linear_model import PassiveAggressiveClassifier

# Create and train the Passive Aggressive Classifier
PAC = PassiveAggressiveClassifier(random_state=0,C=0.1)
PAC.fit(xv_train, y_train)

PassiveAggressiveClassifier(C=0.1, random_state=0)

In [40]:
from joblib import dump
dump(PAC, 'PAC.pk1')

['PAC.pk1']

In [41]:
pred_pac = PAC.predict(xv_test)

In [42]:
accuracy = accuracy_score(y_test, pred_pac)
print(" Passive Agressive Classifier Accuracy = ",accuracy)

 Passive Agressive Classifier Accuracy =  0.9228


In [43]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

cm_pac = confusion_matrix(y_test, pred_pac)
print("Confusion Matrix for PAC :")
print(cm_pac)

# Assuming cm_rf is the confusion matrix from your random forest predictions
tn, fp, fn, tp = cm_pac.ravel()

precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Confusion Matrix for PAC :
[[1113   99]
 [  94 1194]]
Precision: 0.9234338747099768
Recall: 0.9270186335403726
F1 Score: 0.9252227818674932


In [44]:
def predict_news(input_text):
    input_text = preprocessing(input_text)
    input_vector = vectorization.transform([input_text])
    prediction = PAC.predict(input_vector)
    return "Fake" if prediction[0] == 0 else "Real"

input_text = " "
prediction = predict_news(input_text)
print(f"The input text is predicted as: {prediction}")

The input text is predicted as: Real
